apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-backup-sa
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: pg-backup@vjn-devops-with-kubernetes.iam.gserviceaccount.com
# Remember to create a Workload Identity Binding between the Kubernetes Service Account and the GCP Service Account for it to work!
# This has been exluded from the production overlay as it only needs to be done once per GCP project.
