# LoadBalancer service for wikipedia-frontend
apiVersion: v1
kind: Service
metadata:
  name: wikipedia-frontend-lb
  namespace: wikipedia-with-sidecar
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: wikipedia-server
  ports:
    - port: 80
      targetPort: 80
